development:
  dream_state_compaction:
    class: DreamStateCompactionJob
    queue: default
    schedule: every hour
  embedding_backfill:
    class: EmbeddingScheduledBackfillJob
    queue: low_priority
    schedule: every day at 4am

production:
  garbage_collection:
    class: GarbageCollectionJob
    queue: default
    schedule: at 2pm every day
  dream_state_compaction:
    class: DreamStateCompactionJob
    queue: default
    schedule: at 3am every day
  # NOTE: All times are in Greenwich Mean Time (GMT)
  database_backup_at_13:
    class: DatabaseBackupJob
    queue: low_priority
    schedule: every day at 1pm
  database_backup_at_17:
    class: DatabaseBackupJob
    queue: low_priority
    schedule: every day at 5pm
  embedding_backfill:
    class: EmbeddingScheduledBackfillJob
    queue: low_priority
    schedule: at 4am every day
